In [2]:
pip install git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI

  Cloning https://github.com/waleedka/coco.git to /tmp/pip-req-build-8nm9ol9c
  Running command git clone -q https://github.com/waleedka/coco.git /tmp/pip-req-build-8nm9ol9c
  Created wheel for pycocotools: filename=pycocotools-2.0-cp37-cp37m-linux_x86_64.whl size=264148 sha256=83950982526acbc0de37ca7c0b30698b383d88573419ac5b1c2d88e7346605fc
  Stored in directory: /tmp/pip-ephem-wheel-cache-s2snsbmh/wheels/26/53/cb/6a7cdd6bcb0f192dead045f897d3d4e05641492181968447ba
Successfully built pycocotools
  Attempting uninstall: pycocotools
    Found existing installation: pycocotools 2.0.4
    Uninstalling pycocotools-2.0.4:
      Successfully uninstalled pycocotools-2.0.4


In [4]:
from pycocotools.coco import COCO

In [7]:
import json
import numpy as np
from pycocotools import mask
from skimage import measure

In [11]:
ground_truth_binary_mask = np.array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
                                     [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
                                     [  0,   0,   0,   0,   0,   1,   1,   1,   0,   0],
                                     [  0,   0,   0,   0,   0,   1,   1,   1,   0,   0],
                                     [  0,   0,   0,   0,   0,   1,   1,   1,   0,   0],
                                     [  0,   0,   0,   0,   0,   1,   1,   1,   0,   0],
                                     [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0],
                                     [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
                                     [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=np.uint8)

In [12]:
fortran_ground_truth_binary_mask = np.asfortranarray(ground_truth_binary_mask)
fortran_ground_truth_binary_mask

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [14]:
encoded_ground_truth = mask.encode(fortran_ground_truth_binary_mask)
encoded_ground_truth

{'counts': b'61X13mN000`0', 'size': [9, 10]}

In [16]:
mask.decode(encoded_ground_truth)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [21]:
import cv2
rle={'size': [9, 10], 'counts': b'61X13mN000`0'}

In [19]:
dec_rle= mask.decode(rle) * 255
dec_rle

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 255, 255, 255,   0,   0],
       [  0,   0,   0,   0,   0, 255, 255, 255,   0,   0],
       [  0,   0,   0,   0,   0, 255, 255, 255,   0,   0],
       [  0,   0,   0,   0,   0, 255, 255, 255,   0,   0],
       [255,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=uint8)

In [20]:
cv2.imwrite("segmentation.png", dec_rle)

True